name: ci

on: push

env:
  PACKAGE_NAME: '@now-deno/ci'

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: ['12.x']
        deno: ['1.0.0']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Update package version and tag
        run: deno run --unstable --allow-env --allow-read --allow-write .github/workflows/update-version.ts
      - name: Publish to npm
        run: |
          mv .github/workflows/.npmrc .
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  test:
    needs: build
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        node: ['12.x']
        deno: ['1.0.0']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: test-${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1
      - name: Setup deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ matrix.deno }}
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: yarn install
      - name: Install vercel
        run: npm i -g vercel
        if: matrix.os == 'windows-latest'
      - name: Update package version and tag
        run: deno run --unstable --allow-env --allow-read --allow-write .github/workflows/update-version.ts
      - name: Run tests
        run: deno test --unstable --allow-env --allow-write --allow-net --allow-run .github/workflows/tests.ts
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
